### ISSUE TITLE
cannot install in ubuntu 18

### ISSUE THREAD

**Issue by lianghongzhuo** [linuxdeepin/dtkgui#6]
Hi,
I try to compile dtkgui in ubuntu 18, but get the following error when run qmake:
```
dtkgui.pro:1: Cannot find feature dtk_lib
```
I installed all the dependency list in `debian/control` using `apt-get`:
```
 debhelper (>= 9), pkg-config, 
 qtbase5-private-dev, qtbase5-dev-tools, libqt5x11extras5-dev,
 libdtkcore-dev,
 librsvg2-dev
```

**Comment by BLumia** [comment]
Sorry for the super late reply since we're not look into issues that were created outside the developer-center repo.

You need to build and install dtkcommon before trying to build dtkgui, btw, we recommended you upgrade the OS if possible since we no longer support older Qt version.

If you still have related issue, please consider create an issue or discussion thread at the [developer-center](https://github.com/linuxdeepin/developer-center) repo. Thanks!
